site_name: AWS Serverless Hands-on
repo_name: fujiwaki/serverless_hands_on_doc
repo_url: https://github.com/fujiwaki/serverless_hands_on_doc
copyright: Copyright &copy; 2024 Yasuhiro Fujiwaki

nav:
  - Home: index.md
  - Hands-on: contents/
  - Appendix: appendix/
  - memo: memo.md

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
    - scheme: default
      toggle:
        icon: material/toggle-switch
  font:
    text: Fira Sans
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy

plugins:
  - search
  - section-index
  - literate-nav:
      implicit_index: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
